plugins {
    id 'java'
    alias(libs.plugins.spring.boot)
    alias(libs.plugins.spring.dependency.management)
}

group = 'io.github.lzh2587379717.cs2'
description = 'cs2-gsi-eventengine'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(libs.versions.java.get() as int)
    }
}

dependencies {
    implementation(libs.spring.boot.starter)
    testImplementation(libs.spring.boot.starter.test)
    testRuntimeOnly(libs.junit.platform.launcher)
}

springBoot {
    buildInfo() {
        // Exclude build timestamp to ensure build reproducibility
        excludes = ['time']
    }
}

tasks.named('test', Test) {
    useJUnitPlatform()
}
